name: Workflow for Codecov
on: [push, pull_request]
jobs:
  codecov-run:
    runs-on: ubuntu-latest
    # Add container to allow connection to local server for app integration test
    # https://stackoverflow.com/questions/74332455/connection-refused-for-local-server-in-github-actions-workflow
    container: 
      image: ubuntu
      ports:
        # Opens tcp port 7860 on the host and container
        - 7860:7860
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pip
        run: |
          apt-get update
          apt-get install -y python3-pip
      - name: Set up Python virtual environment
        run: |
          apt-get install -y python3-venv
          python -m venv .venv
      # Every run has a default PATH, so sctivate virtual environment in every run
      # https://stackoverflow.com/questions/74668349/how-to-activate-a-virtualenv-in-a-github-action
      - name: Install dependencies
        run: |
          . .venv/bin/activate
          pip install -r requirements.txt
      - name: Run tests and collect coverage
        # Add flag to ignore errors (-i)
        # https://stackoverflow.com/questions/2386975/no-source-for-code-message-in-coverage-py
        run: |
          . .venv/bin/activate
          coverage run -m unittest discover
          coverage report -m -i
          coverage xml -i
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
